(()=>{
  function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn()}
  ready(()=>{
    const wait=setInterval(()=>{
      if(typeof products==='undefined'||typeof K==='undefined'||!document.getElementById('products'))return;
      clearInterval(wait);
      const style=document.createElement('style');style.textContent=`.bc-generate{margin-top:7px;width:100%;border:1px dashed color-mix(in srgb,var(--p) 45%,var(--line));background:color-mix(in srgb,var(--p) 6%,var(--card));color:var(--p);border-radius:12px;padding:9px 11px;font-weight:850}.bc-toolbar{display:flex;gap:8px;margin:0 0 12px;flex-wrap:wrap}.bc-toolbar button{border:0;border-radius:13px;padding:11px 14px;background:linear-gradient(135deg,var(--p),var(--p2));color:#fff;font-weight:900}.bc-modal{position:fixed;inset:0;z-index:100001;display:none;align-items:center;justify-content:center;padding:18px;background:#0f172a99;backdrop-filter:blur(8px)}.bc-modal.show{display:flex}.bc-card{width:min(96vw,760px);max-height:88vh;overflow:auto;background:var(--card);color:var(--ink);border-radius:24px;padding:18px}.bc-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:14px}.bc-head h2{margin:0;font-size:22px}.bc-close{width:40px;height:40px;border:0;border-radius:12px;background:var(--bg);color:var(--ink);font-size:22px}.bc-row{display:grid;grid-template-columns:minmax(0,1fr) 80px;gap:9px;align-items:center;padding:12px 0;border-bottom:1px solid var(--line)}.bc-row strong,.bc-row small{display:block}.bc-row small{color:var(--muted);margin-top:2px}.bc-actions{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr;gap:8px}.bc-actions button{border:0;border-radius:11px;padding:11px;background:var(--p);color:#fff;font-weight:850}.bc-actions .bc-img{background:var(--card);color:var(--p);border:1px solid var(--p)}.bc-status{display:inline-flex;margin-top:5px;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:900}.bc-ok{background:#dcfce7;color:#166534}.bc-bad{background:#fee2e2;color:#991b1b}.bc-note{margin:0 0 12px;padding:10px 12px;border:1px solid var(--line);border-radius:13px;font-size:12px;color:var(--muted)}.bc-empty{padding:24px;text-align:center;color:var(--muted)}`;document.head.appendChild(style);
      function checkDigit12(s){let sum=0;for(let i=0;i<12;i++)sum+=(+s[i])*(i%2===0?1:3);return String((10-sum%10)%10)}
      function valid(code){code=String(code||'').trim();return /^\d{13}$/.test(code)&&checkDigit12(code.slice(0,12))===code[12]}
      function uniqueEAN(){let c;do{const b=('20'+Date.now().toString().slice(-8)+Math.floor(Math.random()*100).toString().padStart(2,'0')).slice(0,12);c=b+checkDigit12(b)}while(products.some(p=>String(p.barcode||'')===c));return c}
      function persist(){try{localStorage.setItem(K.products,JSON.stringify(products.map(p=>{const c={...p};delete c.image;return c})));if(typeof save==='function')save()}catch(e){}}
      function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
      function format(c){return valid(c)?'EAN13':'CODE128'}
      function loadLib(){return new Promise((ok,no)=>{if(window.JsBarcode)return ok();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jsbarcode@3.11.6/dist/JsBarcode.all.min.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
      async function ensure(p){await loadLib();if(!p.barcode)p.barcode=uniqueEAN();try{const c=document.createElement('canvas');JsBarcode(c,String(p.barcode),{format:format(p.barcode)});persist();return String(p.barcode)}catch(e){p.barcode=uniqueEAN();persist();return String(p.barcode)}}
      const input=document.getElementById('barcode');if(input&&!document.getElementById('bcGenerateOne')){const b=document.createElement('button');b.type='button';b.id='bcGenerateOne';b.className='bc-generate';b.textContent='✨ Generar código EAN-13 escaneable';input.after(b);b.onclick=()=>{input.value=uniqueEAN();input.dispatchEvent(new Event('input',{bubbles:true}))}}
      const section=document.getElementById('products'),toolbar=section.querySelector('.toolbar');if(toolbar&&!document.getElementById('bcToolbar')){const w=document.createElement('div');w.id='bcToolbar';w.className='bc-toolbar';w.innerHTML='<button type="button">🏷️ Códigos de barras</button>';toolbar.after(w);w.firstChild.onclick=()=>openManager()}
      const modal=document.createElement('div');modal.className='bc-modal';modal.innerHTML='<div class="bc-card"><div class="bc-head"><div><h2>Códigos de barras</h2><div class="meta">Genera, guarda como imagen o imprime.</div></div><button class="bc-close">×</button></div><div class="bc-note">La opción <b>Imagen PNG</b> crea una etiqueta en alta calidad para guardarla, compartirla o imprimirla en otro lugar.</div><div id="bcList"></div></div>';document.body.appendChild(modal);modal.querySelector('.bc-close').onclick=()=>modal.classList.remove('show');
      function openManager(){render();modal.classList.add('show')}
      function render(){const list=modal.querySelector('#bcList');if(!products.length){list.innerHTML='<div class="bc-empty">Primero crea un producto.</div>';return}list.innerHTML=products.map(p=>`<div class="bc-row" data-id="${p.id}"><div><strong>${esc(p.name||'Producto')}</strong><small>${esc(p.barcode||'Sin código')}</small><span class="bc-status ${p.barcode?'bc-ok':'bc-bad'}">${p.barcode?'✓ Escaneable':'Sin código'}</span></div><input type="number" min="1" max="200" value="1"><div class="bc-actions"><button class="bc-img">🖼️ Imagen PNG</button><button class="bc-print">🖨️ Imprimir</button></div></div>`).join('');list.querySelectorAll('.bc-row').forEach(r=>{const p=products.find(x=>String(x.id)===r.dataset.id);r.querySelector('.bc-img').onclick=()=>imagePNG(p);r.querySelector('.bc-print').onclick=()=>printLabels(p,Math.max(1,parseInt(r.querySelector('input').value)||1))})}
      async function imagePNG(p){let code;try{code=await ensure(p)}catch{return alert('No se pudo cargar el generador. Revisa tu conexión.')}render();const canvas=document.createElement('canvas');canvas.width=1400;canvas.height=760;const x=canvas.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,canvas.width,canvas.height);x.fillStyle='#000';x.textAlign='center';x.font='bold 52px Arial';x.fillText(p.name||'Producto',700,85);const bc=document.createElement('canvas');JsBarcode(bc,code,{format:format(code),width:4,height:240,displayValue:true,fontSize:38,textMargin:12,margin:28,background:'#fff',lineColor:'#000'});x.drawImage(bc,(1400-bc.width)/2,130);x.font='bold 58px Arial';x.fillText('S/ '+Number(p.sellPrice||0).toFixed(2),700,650);x.font='28px Arial';x.fillText(valid(code)?'EAN-13':'CODE128',700,710);const url=canvas.toDataURL('image/png');const a=document.createElement('a');a.href=url;a.download='codigo-'+String(p.name||'producto').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.png';document.body.appendChild(a);a.click();a.remove()}
      async function printLabels(p,qty){let code;try{code=await ensure(p)}catch{return alert('No se pudo preparar el código.')}const labels=[];for(let i=0;i<qty;i++){const c=document.createElement('canvas');JsBarcode(c,code,{format:format(code),width:3,height:90,displayValue:true,fontSize:20,margin:14});labels.push(`<div style="text-align:center;border:1px dashed #bbb;padding:12px"><b>${esc(p.name||'Producto')}</b><br><img style="max-width:100%" src="${c.toDataURL()}"><br><b>S/ ${Number(p.sellPrice||0).toFixed(2)}</b></div>`)}const w=window.open('','_blank');if(!w)return alert('Permite ventanas emergentes para imprimir.');w.document.write(`<html><body style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px">${labels.join('')}<script>onload=()=>print()<\/script></body></html>`);w.document.close()}
    },120)
  })
})();