(()=>{
  if(window.__vareliaBulkScanInitialized)return;
  window.__vareliaBulkScanInitialized=true;
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();
  ready(()=>{
    const nav=document.querySelector('.nav'),main=document.querySelector('main.content');
    if(!nav||!main)return;

    const style=document.createElement('style');style.textContent=`
      .bulkHero{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;padding:18px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(135deg,color-mix(in srgb,var(--p) 9%,var(--card)),var(--card));box-shadow:var(--shadow);margin-bottom:14px}.bulkMode{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;background:var(--bg);padding:5px;border-radius:14px}.bulkMode button{border:0;border-radius:11px;padding:11px 14px;font-weight:900;background:transparent;color:var(--ink)}.bulkMode button.active{background:var(--card);color:var(--p);box-shadow:0 4px 14px #0001}.bulkStats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.bulkStat{padding:13px;border:1px solid var(--line);border-radius:15px;background:var(--card)}.bulkStat small{display:block;color:var(--muted)}.bulkStat strong{font-size:23px}.bulkRow{display:grid;grid-template-columns:62px minmax(0,1fr) auto;gap:12px;align-items:center;padding:12px;border:1px solid var(--line);border-radius:17px;background:var(--card);box-shadow:var(--shadow)}.bulkImg{width:62px;height:62px;border-radius:13px;object-fit:cover;background:var(--bg);display:grid;place-items:center;color:var(--muted);font-size:10px}.bulkQty{display:flex;align-items:center;gap:7px}.bulkQty button{width:38px;height:38px;border:1px solid var(--line);border-radius:11px;background:var(--card);font-weight:950;color:var(--ink)}.bulkQty strong{min-width:48px;text-align:center;font-size:18px}.bulkPositive{color:#047857}.bulkNegative{color:#b91c1c}.bulkSale{color:var(--p)}.bulkBottom{position:sticky;bottom:10px;margin-top:14px;padding:12px;border:1px solid var(--line);border-radius:18px;background:color-mix(in srgb,var(--card) 94%,transparent);backdrop-filter:blur(12px);box-shadow:0 14px 34px #0002;display:grid;grid-template-columns:1fr 1fr;gap:9px}.bulkScanner{width:min(94vw,680px)}#bulkReader{min-height:300px;background:#000;border-radius:18px;overflow:hidden}.bulkScanHint{color:var(--muted);font-size:13px;margin:8px 0 12px}.bulkFlash{animation:bulkflash .25s ease}@keyframes bulkflash{50%{transform:scale(.985);background:color-mix(in srgb,var(--p) 10%,var(--card))}}@media(max-width:600px){.bulkHero{grid-template-columns:1fr}.bulkMode{grid-template-columns:1fr}.bulkStats{grid-template-columns:1fr 1fr}.bulkRow{grid-template-columns:54px minmax(0,1fr)}.bulkImg{width:54px;height:54px}.bulkQty{grid-column:1/-1;justify-content:flex-end}.bulkBottom{grid-template-columns:1fr}}
    `;document.head.appendChild(style);

    const bulkBtn=document.createElement('button');bulkBtn.type='button';bulkBtn.dataset.view='bulkScan';bulkBtn.innerHTML='📲 Ajuste rápido';
    const salesBtn=nav.querySelector('[data-view="sales"]');salesBtn?nav.insertBefore(bulkBtn,salesBtn):nav.appendChild(bulkBtn);

    const section=document.createElement('section');section.id='bulkScan';section.className='view';section.innerHTML=`
      <div class="head"><div><h2>Ajuste rápido por escaneo</h2><p class="notice">Escanea varios productos para sumar stock, restar stock o preparar una venta rápida.</p></div></div>
      <div class="bulkHero"><div><strong style="font-size:18px">¿Qué quieres hacer?</strong><div class="notice">Cada lectura agrega 1 unidad del producto.</div></div><div class="bulkMode"><button type="button" class="active" data-bulkmode="add">➕ Sumar</button><button type="button" data-bulkmode="subtract">➖ Restar</button><button type="button" data-bulkmode="sale">🛒 Vender</button></div></div>
      <div class="toolbar"><button class="btn primary" type="button" id="bulkStartScan">📷 Empezar a escanear</button><input id="bulkManualCode" inputmode="numeric" placeholder="Código manual"><button class="btn secondary" type="button" id="bulkManualAdd">Agregar código</button></div>
      <div class="bulkStats"><div class="bulkStat"><small>Productos diferentes</small><strong id="bulkDifferent">0</strong></div><div class="bulkStat"><small>Unidades</small><strong id="bulkUnits">0</strong></div><div class="bulkStat"><small>Modo actual</small><strong id="bulkModeLabel">Sumar</strong></div><div class="bulkStat"><small>Total venta</small><strong id="bulkSaleTotal">S/ 0.00</strong></div></div>
      <div class="list" id="bulkList"><div class="empty">Todavía no has escaneado productos.</div></div>
      <div class="bulkBottom"><button class="btn secondary" type="button" id="bulkClear">Limpiar</button><button class="btn primary" type="button" id="bulkApply">✓ Aplicar al inventario</button></div>
    `;main.appendChild(section);

    const dialog=document.createElement('dialog');dialog.id='bulkScannerDialog';dialog.className='bulkScanner';dialog.innerHTML=`<div class="modal"><div class="modalhead"><h2>Escanear productos</h2><button class="close" id="bulkCloseScanner">×</button></div><div class="bulkScanHint">Puedes escanear uno tras otro. Cada lectura se agrega automáticamente.</div><div id="bulkReader"></div><div style="display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:12px"><span class="meta" id="bulkLastScan">Esperando código…</span><button class="btn secondary" type="button" id="bulkFinishScan">Terminar</button></div></div>`;document.body.appendChild(dialog);

    let mode='add',session=new Map(),scanner=null,starting=false,lastCode='',lastAt=0;
    const $=id=>document.getElementById(id),norm=v=>String(v??'').trim().replace(/[^0-9A-Za-z]/g,'').toUpperCase();
    function equivalent(a,b){a=norm(a);b=norm(b);if(a===b)return true;const ad=a.replace(/\D/g,''),bd=b.replace(/\D/g,'');return !!ad&&!!bd&&(ad.replace(/^0+/,'')===bd.replace(/^0+/,'')||(ad.length>=12&&bd.length>=12&&ad.slice(-12)===bd.slice(-12)))}
    function findProduct(code){try{return products.find(p=>equivalent(p.barcode,code))||null}catch{return null}}
    function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    function qtyOf(x){return Math.abs(x.delta||0)}
    function saleTotal(){return [...session.values()].reduce((a,x)=>a+qtyOf(x)*(+x.product.sellPrice||0),0)}
    function render(){
      const vals=[...session.values()];$('bulkDifferent').textContent=vals.length;$('bulkUnits').textContent=vals.reduce((a,x)=>a+qtyOf(x),0);$('bulkModeLabel').textContent=mode==='add'?'Sumar':mode==='subtract'?'Restar':'Vender';$('bulkSaleTotal').textContent='S/ '+(mode==='sale'?saleTotal():0).toFixed(2);$('bulkApply').textContent=mode==='sale'?'💳 Pagar / finalizar venta':'✓ Aplicar al inventario';
      $('bulkList').innerHTML=vals.length?vals.map(x=>{const p=x.product,q=qtyOf(x),img=p.image?`<img class="bulkImg" src="${p.image}" alt="">`:'<div class="bulkImg">Sin imagen</div>';let detail;if(mode==='sale'){detail=`<div class="bulkSale" style="font-weight:900;margin-top:3px">${q} × S/ ${Number(p.sellPrice||0).toFixed(2)} = S/ ${(q*(+p.sellPrice||0)).toFixed(2)}</div>`}else{const newStock=(+p.stock||0)+x.delta;detail=`<div class="${x.delta>=0?'bulkPositive':'bulkNegative'}" style="font-weight:900;margin-top:3px">${x.delta>=0?'+':''}${x.delta} → Nuevo stock: ${newStock}</div>`}return `<div class="bulkRow" data-bulkid="${esc(p.id)}">${img}<div><strong>${esc(p.name)}</strong><div class="meta">${esc(p.barcode||'Sin código')} · Stock: ${Number(p.stock||0)} ${esc(p.unit||'Unidad')}</div>${detail}</div><div class="bulkQty"><button type="button" data-bulkminus="${esc(p.id)}">−</button><strong>${q}</strong><button type="button" data-bulkplus="${esc(p.id)}">+</button></div></div>`}).join(''):'<div class="empty">Todavía no has escaneado productos.</div>';
    }
    function addCode(raw){const code=norm(raw);if(!code)return;const now=Date.now();if(code===lastCode&&now-lastAt<650)return;lastCode=code;lastAt=now;const p=findProduct(code);if(!p){window.vareliaSound?.('error');window.vareliaToast?.('Código no registrado: '+code,'error');return}const current=session.get(p.id)||{product:p,delta:0};if(mode==='sale'){const next=qtyOf(current)+1;if(next>(+p.stock||0)){window.vareliaSound?.('error');window.vareliaToast?.('No hay más stock disponible de '+p.name,'warn');return}current.delta=next}else{const step=mode==='add'?1:-1;if(step<0&&(+p.stock||0)+current.delta<=0){window.vareliaSound?.('error');window.vareliaToast?.('No puedes dejar stock negativo.','warn');return}current.delta+=step}if(current.delta===0)session.delete(p.id);else session.set(p.id,current);window.vareliaSound?.('scan');$('bulkLastScan').textContent='✓ '+p.name;render();const row=document.querySelector(`[data-bulkid="${CSS.escape(String(p.id))}"]`);if(row){row.classList.remove('bulkFlash');requestAnimationFrame(()=>row.classList.add('bulkFlash'));row.scrollIntoView({behavior:'smooth',block:'nearest'})}}
    function loadLib(){return new Promise((resolve,reject)=>{if(window.Html5Qrcode)return resolve();let s=document.querySelector('script[data-varelia-html5qrcode]');if(s){s.addEventListener('load',resolve,{once:true});s.addEventListener('error',reject,{once:true});return}s=document.createElement('script');s.dataset.vareliaHtml5qrcode='1';s.src='https://unpkg.com/html5-qrcode@2.3.8/html5-qrcode.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
    async function stopScan(){const s=scanner;scanner=null;if(!s)return;try{await s.stop()}catch{}try{await s.clear()}catch{}}
    async function startScan(){if(starting)return;starting=true;try{await stopScan();await loadLib();if(!dialog.open)dialog.showModal();$('bulkReader').innerHTML='';scanner=new Html5Qrcode('bulkReader');let cam={facingMode:'environment'};try{const cams=await Html5Qrcode.getCameras();if(cams?.length){const back=cams.find(c=>/back|rear|environment|trasera|posterior/i.test(c.label||''))||cams[cams.length-1];if(back?.id)cam=back.id}}catch{}await scanner.start(cam,{fps:12,qrbox:{width:280,height:145},aspectRatio:1.777},text=>addCode(text),()=>{})}catch(e){console.error(e);window.vareliaSound?.('error');alert('No se pudo iniciar la cámara. Verifica el permiso de cámara e inténtalo nuevamente.');try{dialog.close()}catch{}}finally{starting=false}}
    async function closeScan(){await stopScan();try{if(dialog.open)dialog.close()}catch{}}

    section.querySelector('.bulkMode').onclick=e=>{const b=e.target.closest('[data-bulkmode]');if(!b)return;if(session.size&&!confirm('Cambiar de modo limpiará el conteo actual. ¿Continuar?'))return;session.clear();mode=b.dataset.bulkmode;section.querySelectorAll('[data-bulkmode]').forEach(x=>x.classList.toggle('active',x===b));render()};
    $('bulkStartScan').onclick=startScan;$('bulkCloseScanner').onclick=closeScan;$('bulkFinishScan').onclick=closeScan;dialog.addEventListener('cancel',e=>{e.preventDefault();closeScan()});
    $('bulkManualAdd').onclick=()=>{addCode($('bulkManualCode').value);$('bulkManualCode').value='';$('bulkManualCode').focus()};$('bulkManualCode').addEventListener('keydown',e=>{if(e.key==='Enter')$('bulkManualAdd').click()});
    $('bulkList').onclick=e=>{const plus=e.target.closest('[data-bulkplus]'),minus=e.target.closest('[data-bulkminus]');const id=plus?.dataset.bulkplus||minus?.dataset.bulkminus;if(!id)return;const item=session.get(id);if(!item)return;let q=qtyOf(item)+(plus?1:-1);if(q<=0){session.delete(id);render();return}if(mode==='sale'&&q>(+item.product.stock||0)){window.vareliaSound?.('error');return window.vareliaToast?.('No hay suficiente stock.','warn')}if(mode==='sale')item.delta=q;else item.delta=(mode==='add'?q:-q);render();window.vareliaSound?.('add')};
    $('bulkClear').onclick=()=>{if(!session.size)return;if(confirm('¿Limpiar todo el conteo actual?')){session.clear();render()}};
    $('bulkApply').onclick=()=>{if(!session.size)return window.vareliaToast?.('No hay productos agregados.','warn');if(mode==='sale'){const items=[];for(const {product,delta} of session.values()){const q=qtyOf({delta});if(q>(+product.stock||0)){window.vareliaSound?.('error');return alert('No hay suficiente stock de '+product.name+'.')}items.push({id:product.id,name:product.name,price:+product.sellPrice||0,qty:q})}const total=items.reduce((a,i)=>a+i.price*i.qty,0);for(const i of items){const p=products.find(x=>x.id===i.id);p.stock=(+p.stock||0)-i.qty}try{sales.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,7),date:new Date().toISOString(),items,total});if(typeof save==='function')save()}catch(e){console.error(e);return alert('No se pudo guardar la venta.')}window.vareliaSound?.('sale');window.vareliaToast?.('Venta registrada · S/ '+total.toFixed(2));session.clear();render();return}for(const {product,delta} of session.values())if((+product.stock||0)+delta<0){window.vareliaSound?.('error');return alert('No se puede aplicar porque '+product.name+' quedaría con stock negativo.')}for(const {product,delta} of session.values())product.stock=(+product.stock||0)+delta;try{if(typeof save==='function')save()}catch(e){console.error(e);return alert('No se pudieron guardar los cambios.')}window.vareliaSound?.('sale');window.vareliaToast?.('Inventario actualizado correctamente.');session.clear();render()};

    bulkBtn.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v===section));document.querySelectorAll('.nav [data-view]').forEach(b=>b.classList.toggle('active',b===bulkBtn));try{history.replaceState(null,'',location.pathname+location.search+'#escaneo-multiple')}catch{}if(innerWidth<=980){document.getElementById('sidebar')?.classList.remove('open');document.getElementById('overlay')?.classList.remove('show')}scrollTo({top:0,behavior:'smooth'})},true);
    document.addEventListener('click',e=>{const b=e.target.closest('.nav [data-view]');if(b&&b!==bulkBtn&&dialog.open)closeScan()},true);
    window.addEventListener('pagehide',stopScan);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopScan()});
    if(location.hash==='#escaneo-multiple')setTimeout(()=>bulkBtn.click(),100);
    render();
  });
})();