(()=>{
if(window.__vareliaCatalogOrders)return;window.__vareliaCatalogOrders=true;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'S/ '+Number(n||0).toFixed(2);
let sb=null,businessId='',userId='',role='',orders=[];
const style=document.createElement('style');style.textContent='.vorderCard{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:15px;box-shadow:var(--shadow)}.vorderTop{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.vorderStatus{display:inline-block;padding:6px 10px;border-radius:999px;font-size:12px;font-weight:900}.vorderPending{background:#fef3c7;color:#92400e}.vorderPaid{background:#d1fae5;color:#047857}.vorderMeta{font-size:13px;color:var(--muted);line-height:1.55;margin-top:8px}.vorderItems{margin:11px 0;padding-top:9px;border-top:1px solid var(--line);font-size:13px;line-height:1.55}.vorderActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.vorderActions button{flex:1;min-width:150px}';document.head.appendChild(style);
function section(){return document.getElementById('catalogOrders')}
function ensureUI(){
 const sales=document.getElementById('sales');if(!sales)return false;
 if(!section()){const sec=document.createElement('section');sec.id='catalogOrders';sec.className='view';sec.innerHTML='<div class="head"><div><h2>Pedidos del catálogo</h2><p class="notice">Confirma el pago únicamente después de verificar que recibiste el dinero.</p></div><button class="btn secondary" id="vordersRefresh">Actualizar</button></div><div class="list" id="vordersList"><div class="empty">Cargando pedidos…</div></div>';sales.parentNode.insertBefore(sec,sales);sec.querySelector('#vordersRefresh').onclick=load}
 const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-view="catalogOrders"]')){const b=document.createElement('button');b.dataset.view='catalogOrders';b.innerHTML='🛍️ Pedidos del catálogo';const salesBtn=nav.querySelector('[data-view="sales"]');salesBtn?nav.insertBefore(b,salesBtn.nextSibling):nav.appendChild(b);b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav button[data-view]').forEach(v=>v.classList.remove('active'));section().classList.add('active');b.classList.add('active');load()}}
 return true
}
async function scope(){sb=window.vareliaSupabase;if(!sb)return false;const {data:u}=await sb.auth.getUser();if(!u?.user)return false;userId=u.user.id;const {data:p,error}=await sb.from('profiles').select('business_id,role').eq('id',userId).maybeSingle();if(error||!p)return false;businessId=String(p.business_id||'');role=String(p.role||'');return !!businessId}
function itemText(i){const c=Array.isArray(i.characteristics)&&i.characteristics.length?' · '+i.characteristics.map(esc).join(' · '):'';return '<div><b>'+esc(i.name)+'</b>'+c+'<br>Cantidad: '+esc(i.qty)+' × '+money(i.unit_price)+' = <b>'+money(i.subtotal)+'</b></div>'}
function render(){const box=document.getElementById('vordersList');if(!box)return;if(!orders.length){box.innerHTML='<div class="empty">Aún no hay pedidos del catálogo.</div>';return}box.innerHTML=orders.map(o=>'<div class="vorderCard"><div class="vorderTop"><div><b>'+esc(o.order_code)+'</b><div class="vorderMeta">'+new Date(o.created_at).toLocaleString('es-PE')+'</div></div><span class="vorderStatus '+(o.payment_status==='paid'?'vorderPaid':'vorderPending')+'">'+(o.payment_status==='paid'?'✓ PAGADO':'PAGO PENDIENTE')+'</span></div><div class="vorderMeta"><b>'+esc(o.customer_name)+'</b> · '+esc(o.customer_phone)+'<br>'+esc(o.customer_city)+(o.customer_address?' · '+esc(o.customer_address):'')+'<br>Entrega: '+esc(o.delivery_label)+' · Pago: '+esc(o.payment_method)+'</div><div class="vorderItems">'+(Array.isArray(o.items)?o.items.map(itemText).join(''): '')+'</div><div style="display:flex;justify-content:space-between;font-weight:900"><span>Total</span><span>'+money(o.total)+'</span></div><div class="vorderActions">'+(o.payment_status==='pending'&&role==='owner'?'<button class="btn ok" data-confirm="'+o.id+'">✓ Confirmar pago</button>':'')+'<button class="btn secondary" data-ticket="'+o.id+'">Comprobante</button></div></div>').join('')}
async function load(){if(!await scope())return;const {data,error}=await sb.from('public_catalog_orders').select('*').eq('business_id',businessId).order('created_at',{ascending:false}).limit(100);if(error){console.error(error);return}orders=data||[];render()}
function ticket(o){const paid=o.payment_status==='paid';const items=(Array.isArray(o.items)?o.items:[]).map(i=>'<div class="item"><b>'+esc(i.name)+'</b>'+(i.characteristics?.length?'<div>'+i.characteristics.map(esc).join(' · ')+'</div>':'')+'<div>Cantidad: '+esc(i.qty)+' × '+money(i.unit_price)+' <b>'+money(i.subtotal)+'</b></div></div>').join('');const html='<!doctype html><html><head><meta charset="utf-8"><title>Comprobante de pedido</title><style>body{font-family:Arial,sans-serif;color:#111;padding:24px}.t{max-width:520px;margin:auto;border:1px solid #ddd;border-radius:16px;padding:24px}h1,h2{text-align:center}.s{text-align:center;font-weight:900;border:2px solid #111;padding:10px;border-radius:10px;margin:14px 0}.item{border-top:1px dashed #aaa;padding:12px 0;line-height:1.5}.r{display:flex;justify-content:space-between;margin:7px 0}.total{font-size:20px;font-weight:900;border-top:2px solid #111;padding-top:12px}.note{text-align:center;font-size:12px;margin-top:20px}.p{width:100%;padding:12px;background:#111;color:#fff;border:0;border-radius:10px;font-weight:800;margin-top:18px}@media print{.p{display:none}.t{border:0}}</style></head><body><div class="t"><h1>Varelia</h1><h2>COMPROBANTE DE PEDIDO</h2><div style="text-align:center;font-weight:800">'+esc(o.order_code)+'</div><div class="s">'+(paid?'✓ PAGO CONFIRMADO':'PAGO PENDIENTE DE CONFIRMACIÓN')+'</div><div><b>Pedido:</b> '+new Date(o.created_at).toLocaleString('es-PE')+'</div>'+(paid?'<div><b>Pago confirmado:</b> '+new Date(o.paid_at).toLocaleString('es-PE')+'</div>':'')+'<div><b>Cliente:</b> '+esc(o.customer_name)+'</div><div><b>Celular:</b> '+esc(o.customer_phone)+'</div><div><b>Distrito/Ciudad:</b> '+esc(o.customer_city)+'</div><div><b>Entrega:</b> '+esc(o.delivery_label)+'</div>'+(o.customer_address?'<div><b>Dirección:</b> '+esc(o.customer_address)+'</div>':'')+'<div><b>Método de pago:</b> '+esc(o.payment_method)+'</div><h3>PRODUCTOS</h3>'+items+'<div class="r"><span>Productos</span><b>'+money(o.subtotal)+'</b></div><div class="r"><span>Envío</span><b>'+(o.delivery_type==='shalom'?'Pago en agencia':money(o.shipping))+'</b></div><div class="r total"><span>TOTAL</span><span>'+money(o.total)+'</span></div><div class="note">'+(paid?'Pago verificado por el negocio.':'Este documento confirma el pedido y no acredita el pago hasta su verificación.')+'</div><button class="p" onclick="window.print()">Guardar como PDF / Imprimir</button></div></body></html>';const w=window.open('','_blank');if(!w)return alert('Permite ventanas emergentes para abrir el comprobante.');w.document.write(html);w.document.close()}
document.addEventListener('click',async e=>{const c=e.target.closest('[data-confirm]');if(c){if(!confirm('¿Ya verificaste que recibiste el pago?'))return;c.disabled=true;const now=new Date().toISOString();const {error}=await sb.from('public_catalog_orders').update({payment_status:'paid',paid_at:now,paid_by:userId}).eq('id',c.dataset.confirm).eq('business_id',businessId);if(error){console.error(error);alert('No se pudo confirmar el pago.');c.disabled=false;return}window.vareliaToast?.('Pago confirmado.','ok');await load();return}const t=e.target.closest('[data-ticket]');if(t){const o=orders.find(x=>x.id===t.dataset.ticket);if(o)ticket(o)}},true);
window.vareliaOpenCatalogOrders=async()=>{ensureUI();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));section()?.classList.add('active');await load()};
let tries=0;const timer=setInterval(async()=>{tries++;if(ensureUI()&&window.vareliaSupabase){clearInterval(timer);await load()}if(tries>100)clearInterval(timer)},150);
})();