(()=>{
if(window.__vareliaCatalogOrders)return;window.__vareliaCatalogOrders=true;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'S/ '+Number(n||0).toFixed(2);
function catalogItemMeasure(i){
 var q=Number(i.qty||0),raw=String(i.sale_unit||i.unit||'').trim().toLowerCase(),unit='';
 var aliases={box:'caja',caja:'caja',blister:'blíster','blíster':'blíster',pill:'pastilla',pastilla:'pastilla',kg:'kg',kilogramo:'kg',g:'g',gramo:'g',unidad:'unidad',unit:'unidad',und:'unidad'};
 unit=aliases[raw]||raw;
 var weight='';
 if(!unit){(Array.isArray(i.characteristics)?i.characteristics:[]).some(function(x){var m=String(x).match(/^Peso:\s*(\d+(?:[.,]\d+)?)\s*(kg|g|gramos?)$/i);if(!m)return false;weight=Number(m[1].replace(',','.'))*(m[2].toLowerCase()==='kg'?1:.001);unit='kg';return true})}
 var amount=q,measure='';
 if(unit==='kg'){amount=weight!==''?weight:q;measure=amount<1?String(Math.round(amount*1000))+' gramos':String(amount).replace('.',',')+' kg'}
 else if(unit==='g'){measure=String(q).replace('.',',')+' gramos'}
 else if(unit){var plural={'unidad':'unidades','caja':'cajas','blíster':'blísteres','pastilla':'pastillas'};measure=String(q).replace('.',',')+' '+(q===1?unit:(plural[unit]||unit))}
 return {unit:unit,quantity:measure||String(q),priceUnit:unit==='g'?'gramo':unit};
}
function catalogItemText(i){var m=catalogItemMeasure(i);return 'Cantidad: '+m.quantity+' · Precio: '+money(i.unit_price)+(m.priceUnit?' por '+m.priceUnit:'')}
function catalogItemHtml(i){var m=catalogItemMeasure(i);return '<b>Cantidad:</b> '+esc(m.quantity)+'<br><b>Precio:</b> <span style="white-space:nowrap">'+money(i.unit_price)+'</span>'+(m.priceUnit?' por '+esc(m.priceUnit):'')}
const receiptLine=i=>'<span>'+catalogItemHtml(i)+'</span>';
let sb=null,businessId='',userId='',role='',orders=[];
const style=document.createElement('style');style.textContent='.vorderCard{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:15px;box-shadow:var(--shadow)}.vorderTop{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.vorderStatus{display:inline-block;padding:6px 10px;border-radius:999px;font-size:12px;font-weight:900}.vorderPending{background:#fef3c7;color:#92400e}.vorderPaid{background:#d1fae5;color:#047857}.vorderMeta{font-size:13px;color:var(--muted);line-height:1.55;margin-top:8px}.vorderItems{margin:11px 0;padding-top:9px;border-top:1px solid var(--line);font-size:13px;line-height:1.55}.vorderActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.vorderActions button{flex:1;min-width:150px}';document.head.appendChild(style);
function section(){return document.getElementById('catalogOrders')}
function ensureUI(){
 const sales=document.getElementById('sales');if(!sales)return false;
 if(!section()){const sec=document.createElement('section');sec.id='catalogOrders';sec.className='view';sec.innerHTML='<div class="head"><div><h2>Pedidos del catálogo</h2><p class="notice">Confirma el pago únicamente después de verificar que recibiste el dinero.</p></div><button class="btn secondary" id="vordersRefresh">Actualizar</button></div><div class="list" id="vordersList"><div class="empty">Cargando pedidos…</div></div>';sales.parentNode.insertBefore(sec,sales);sec.querySelector('#vordersRefresh').onclick=load}
 const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-view="catalogOrders"]')){const b=document.createElement('button');b.dataset.view='catalogOrders';b.innerHTML='🛍️ Pedidos del catálogo';const salesBtn=nav.querySelector('[data-view="sales"]');salesBtn?nav.insertBefore(b,salesBtn.nextSibling):nav.appendChild(b);b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav button[data-view]').forEach(v=>v.classList.remove('active'));section().classList.add('active');b.classList.add('active');load()}}
 return true
}
async function scope(){sb=window.vareliaSupabase;if(!sb)return false;const {data:u}=await sb.auth.getUser();if(!u?.user)return false;userId=u.user.id;const {data:p,error}=await sb.from('profiles').select('business_id,role').eq('id',userId).maybeSingle();if(error||!p)return false;businessId=String(p.business_id||'');role=String(p.role||'');return !!businessId}
function itemText(i){const c=Array.isArray(i.characteristics)&&i.characteristics.length?' · '+i.characteristics.map(esc).join(' · '):'';return '<div><b>'+esc(i.name)+'</b>'+c+'<br>'+catalogItemHtml(i)+' · Subtotal: <b>'+money(i.subtotal)+'</b></div>'}
function render(){const box=document.getElementById('vordersList');if(!box)return;if(!orders.length){box.innerHTML='<div class="empty">Aún no hay pedidos del catálogo.</div>';return}box.innerHTML=orders.map(o=>'<div class="vorderCard"><div class="vorderTop"><div><b>'+esc(o.order_code)+'</b><div class="vorderMeta">'+new Date(o.created_at).toLocaleString('es-PE')+'</div></div><span class="vorderStatus '+(o.payment_status==='paid'?'vorderPaid':'vorderPending')+'">'+(o.payment_status==='paid'?'✓ PAGADO':'PAGO PENDIENTE')+'</span></div><div class="vorderMeta"><b>'+esc(o.customer_name)+'</b> · '+esc(o.customer_phone)+'<br>'+esc(o.customer_city)+(o.customer_address?' · '+esc(o.customer_address):'')+'<br>Entrega: '+esc(o.delivery_label)+' · Pago: '+esc(o.payment_method)+'</div><div class="vorderItems">'+(Array.isArray(o.items)?o.items.map(itemText).join(''): '')+'</div><div style="display:flex;justify-content:space-between;font-weight:900"><span>Total</span><span>'+money(o.total)+'</span></div><div class="vorderActions">'+(o.payment_status==='pending'&&role==='owner'?'<button class="btn ok" data-confirm="'+o.id+'">✓ Confirmar pago</button>':'')+'<button class="btn secondary" data-ticket="'+o.id+'">Comprobante</button></div></div>').join('')}
async function load(){if(!await scope())return;const {data,error}=await sb.from('public_catalog_orders').select('*').eq('business_id',businessId).order('created_at',{ascending:false}).limit(100);if(error){console.error(error);return}orders=data||[];render()}
function ticket(o){
 const paid=o.payment_status==='paid';
 let bs={};try{bs={...(JSON.parse(localStorage.getItem('varelia_video_settings_v1')||'{}')||{}),...(window.vareliaVideoSettings||{})}}catch{bs=window.vareliaVideoSettings||{}}
 const receiptBusinessName=String(bs.businessName||document.getElementById('vareliaBusinessName')?.textContent?.trim()||document.querySelector('.brand h1')?.textContent?.trim()||'Varelia Store');
 const receiptLogo=String(bs.logo||'').trim();
 const logoHtml=receiptLogo?'<div class="vreceiptLogo"><img src="'+esc(receiptLogo)+'" alt="Logo"></div>':'';
 const items=(Array.isArray(o.items)?o.items:[]).map(i=>'<div class="item"><div><b>'+esc(i.name)+'</b></div>'+(i.characteristics?.length?'<div class="muted">'+i.characteristics.map(esc).join(' · ')+'</div>':'')+'<div class="itemqty">'+receiptLine(i)+'<b>'+money(i.subtotal)+'</b></div></div>').join('');
 let sec=document.getElementById('catalogOrderReceipt');
 if(!sec){sec=document.createElement('section');sec.id='catalogOrderReceipt';sec.className='view';document.querySelector('main.content')?.appendChild(sec)}
 sec.innerHTML='<div style="max-width:620px;margin:0 auto;padding:8px 0 28px"><button class="btn secondary" id="vreceiptBack" type="button">← Volver a Pedidos</button><div class="vreceipt">'+logoHtml+'<h1>'+esc(receiptBusinessName)+'</h1><h2>COMPROBANTE DE PEDIDO</h2><div class="code">'+esc(o.order_code)+'</div><div class="status">'+(paid?'✓ PAGO CONFIRMADO':'PAGO PENDIENTE DE CONFIRMACIÓN')+'</div><div class="data"><div><b>Pedido:</b> '+new Date(o.created_at).toLocaleString('es-PE')+'</div>'+(paid?'<div><b>Pago confirmado:</b> '+new Date(o.paid_at).toLocaleString('es-PE')+'</div>':'')+'<div><b>Cliente:</b> '+esc(o.customer_name)+'</div><div><b>Celular:</b> '+esc(o.customer_phone)+'</div><div><b>Distrito/Ciudad:</b> '+esc(o.customer_city)+'</div><div><b>Entrega:</b> '+esc(o.delivery_label)+'</div>'+(o.customer_address?'<div><b>Dirección:</b> '+esc(o.customer_address)+'</div>':'')+'<div><b>Método de pago:</b> '+esc(o.payment_method)+'</div></div><h3>PRODUCTOS</h3>'+items+'<div class="sum"><div><span>Productos</span><b>'+money(o.subtotal)+'</b></div><div><span>Envío</span><b>'+(o.delivery_type==='shalom'?'Pago en agencia':money(o.shipping))+'</b></div><div class="grand"><span>TOTAL</span><b>'+money(o.total)+'</b></div></div><div class="note">'+(paid?'Pago verificado por el negocio.':'Este documento confirma el pedido y no acredita el pago hasta su verificación.')+'</div><div class="actions"><button class="btn secondary" id="vreceiptPrint" type="button">Imprimir / Guardar PDF</button>'+(paid?'':'')+'</div></div></div>';
 if(!document.getElementById('vreceiptCss')){const st=document.createElement('style');st.id='vreceiptCss';st.textContent='.vreceipt{background:#fff;color:#111;border:1px solid #ddd;border-radius:18px;padding:24px;margin-top:12px}.vreceipt h1,.vreceipt h2{text-align:center;margin:4px 0 12px}.vreceiptLogo{text-align:center;margin:0 auto 8px}.vreceiptLogo img{display:block;margin:auto;max-width:110px;max-height:80px;width:auto;height:auto;object-fit:contain}.vreceipt h1{font-size:24px}.vreceipt h2{font-size:18px}.vreceipt .code{text-align:center;font-weight:800}.vreceipt .status{text-align:center;font-weight:900;border:2px solid #111;border-radius:10px;padding:10px;margin:14px 0}.vreceipt .data{line-height:1.5}.vreceipt h3{margin-top:18px}.vreceipt .item{border-top:1px dashed #bbb;padding:11px 0}.vreceipt .itemrow,.vreceipt .sum>div{display:grid;grid-template-columns:1fr auto;gap:18px;align-items:baseline}.vreceipt .itemrow>b:last-child,.vreceipt .sum b{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}.vreceipt .muted{font-size:13px;color:#444;line-height:1.45}.vreceipt .itemqty{display:grid;grid-template-columns:1fr auto;gap:18px;align-items:baseline;font-size:13px;color:#444;line-height:1.45}.vreceipt .itemqty>b{text-align:right;white-space:nowrap;color:#111;font-variant-numeric:tabular-nums}.vreceipt .grand{border-top:2px solid #111;padding-top:10px;margin-top:7px;font-size:19px}.vreceipt .note{text-align:center;font-size:12px;margin:18px 0}.vreceipt .actions{display:flex;gap:8px}.vreceipt .actions button{flex:1}@media(max-width:600px){.vreceipt{padding:16px;border-radius:14px}.vreceipt h1{font-size:22px}.vreceipt h2{font-size:16px}}@media print{body *{visibility:hidden!important}#catalogOrderReceipt,#catalogOrderReceipt *{visibility:visible!important}#catalogOrderReceipt{position:absolute;inset:0;width:100%;background:#fff}.vreceipt{border:0}.vreceipt .actions,#vreceiptBack{display:none!important}}';document.head.appendChild(st)}
 document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));sec.classList.add('active');
 document.getElementById('vreceiptBack').onclick=()=>window.vareliaOpenCatalogOrders?.();
 document.getElementById('vreceiptPrint').onclick=()=>window.print();
}
document.addEventListener('click',async e=>{const c=e.target.closest('[data-confirm]');if(c){if(!confirm('¿Ya verificaste que recibiste el pago?'))return;c.disabled=true;const now=new Date().toISOString();const {error}=await sb.from('public_catalog_orders').update({payment_status:'paid',paid_at:now,paid_by:userId}).eq('id',c.dataset.confirm).eq('business_id',businessId);if(error){console.error(error);alert('No se pudo confirmar el pago.');c.disabled=false;return}window.vareliaToast?.('Pago confirmado.','ok');await load();return}const t=e.target.closest('[data-ticket]');if(t){const o=orders.find(x=>x.id===t.dataset.ticket);if(o)ticket(o)}},true);
window.vareliaOpenCatalogOrders=async()=>{ensureUI();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));section()?.classList.add('active');await load()};
let tries=0;const timer=setInterval(async()=>{tries++;if(ensureUI()&&window.vareliaSupabase){clearInterval(timer);await load()}if(tries>100)clearInterval(timer)},150);
})();