(()=>{
if(window.__vareliaCharacteristics)return;window.__vareliaCharacteristics=true;
const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defs=['Talla','Color','Material','Calidad','Tamaño','Modelo','Grosor','Piezas','Tono','Acabado','Presentación','Marca','Otra'];
const normalize=a=>Array.isArray(a)?a.filter(x=>x&&x.name&&Array.isArray(x.values)&&x.values.length).slice(0,8).map(x=>({name:String(x.name).slice(0,40),values:x.values.filter(v=>v&&String(v.label||v).trim()).slice(0,40).map(v=>typeof v==='string'?{label:v}:{label:String(v.label),color:String(v.color||'')})})):[];

const st=document.createElement('style');st.textContent=`
.vcharBox{border:1px solid var(--line);border-radius:16px;padding:13px;background:var(--bg);display:grid;gap:11px}.vcharHead{display:flex;justify-content:space-between;align-items:center;gap:10px}.vcharHead b{font-size:14px}.vcharRow{border:1px solid var(--line);border-radius:14px;padding:11px;background:var(--card);display:grid;gap:8px}.vcharName{display:grid;grid-template-columns:1fr 1fr;gap:8px}.vcharValues{display:flex;gap:7px;flex-wrap:wrap}.vcharValue{display:flex;gap:5px;align-items:center;border:1px solid var(--line);border-radius:10px;padding:5px 7px;background:var(--bg)}.vcharValue input[type=text]{border:0;padding:5px;background:transparent;min-width:80px}.vcharValue input[type=color]{width:42px;height:42px;padding:2px;border-radius:10px;cursor:pointer}.vcolorQuick{display:flex;gap:5px;flex-wrap:wrap;width:100%}.vcolorQuick button{width:28px;height:28px;border-radius:50%;border:2px solid #fff;box-shadow:0 0 0 1px #cbd5e1;padding:0}.vcharAdd{padding:7px 9px!important;font-size:12px}.vcomboBox{margin-top:10px;border-top:1px solid var(--line);padding-top:10px}.vcomboGrid{display:grid;gap:7px}.vcomboLine{display:grid;grid-template-columns:minmax(0,1fr) 100px;gap:8px;align-items:center}.vcomboLine span{font-size:12px;font-weight:750}.vcomboLine input{width:100%;padding:8px}.vcsDlg{border:0;border-radius:22px;padding:0;width:min(470px,94vw);background:var(--card);color:var(--ink);box-shadow:0 28px 80px #0005}.vcsDlg::backdrop{background:#0f172a99}.vcsBody{padding:18px}.vcsTop{display:flex;justify-content:space-between;gap:12px;align-items:start}.vcsTop h3{margin:0}.vcsTop button{border:0;background:transparent;font-size:28px;color:var(--ink)}.vcsGroup{margin-top:16px}.vcsGroup>strong{display:block;margin-bottom:8px}.vcsOptions{display:flex;flex-wrap:wrap;gap:8px}.vcsOpt{border:1px solid var(--line);border-radius:12px;background:var(--bg);color:var(--ink);padding:10px 12px;font-weight:850;display:flex;align-items:center;gap:7px}.vcsOpt.active{border:2px solid var(--p);background:color-mix(in srgb,var(--p) 9%,var(--card));color:var(--p)}.vcsDot{width:17px;height:17px;border-radius:50%;border:1px solid #0002}.vcsOk{width:100%;margin-top:17px;padding:14px!important}`;document.head.appendChild(st);

let dlg=document.createElement('dialog');dlg.className='vcsDlg';dlg.innerHTML='<div class="vcsBody"><div class="vcsTop"><div><h3 id="vcsTitle">Elige las opciones</h3><small class="notice">Marca lo que el cliente está comprando.</small></div><button type="button" data-vcs-close>×</button></div><div id="vcsGroups"></div><button type="button" class="btn primary vcsOk" id="vcsOk">Continuar</button></div>';document.body.appendChild(dlg);
let pending=null,selected={};
function selectProduct(p,cb){
 const chars=normalize(p?.characteristics);if(!chars.length){cb(p);return}
 pending={p,cb,chars};selected={};dlg.querySelector('#vcsTitle').textContent=p.name||'Elige las opciones';
 dlg.querySelector('#vcsGroups').innerHTML=chars.map((c,i)=>'<div class="vcsGroup" data-ci="'+i+'"><strong>'+esc(c.name)+'</strong><div class="vcsOptions">'+c.values.map((v,j)=>'<button type="button" class="vcsOpt" data-vi="'+j+'">'+(v.color?'<span class="vcsDot" style="background:'+esc(v.color)+'"></span>':'')+esc(v.label)+'</button>').join('')+'</div></div>').join('');
 dlg.showModal();
}
dlg.addEventListener('click',e=>{const b=e.target.closest('.vcsOpt');if(!b)return;const g=b.closest('[data-ci]'),i=+g.dataset.ci,j=+b.dataset.vi;g.querySelectorAll('.vcsOpt').forEach(x=>x.classList.remove('active'));b.classList.add('active');selected[i]=pending.chars[i].values[j]});
dlg.querySelector('[data-vcs-close]').onclick=()=>{dlg.close();pending=null};
dlg.querySelector('#vcsOk').onclick=()=>{if(!pending)return;for(let i=0;i<pending.chars.length;i++)if(!selected[i])return window.vareliaToast?.('Elige '+pending.chars[i].name,'warn');const selection=pending.chars.map((c,i)=>({name:c.name,value:selected[i].label,color:selected[i].color||''}));const label=selection.map(x=>x.name+': '+x.value).join(' · ');const vals=selection.map(x=>x.value),combo=(Array.isArray(pending.p.variantCombinations)?pending.p.variantCombinations:[]).find(c=>JSON.stringify(c.values||[])===JSON.stringify(vals));if(combo&&Number(combo.stock||0)<=0)return window.vareliaToast?.('Esa combinación está agotada.','warn');const clone={...pending.p,__characteristicsSelected:true,selectedCharacteristics:selection,selectionLabel:label,selectedCombination:combo||null,stock:combo?Number(combo.stock||0):pending.p.stock};const cb=pending.cb;pending=null;dlg.close();cb(clone)};
window.VareliaCharacteristics={select:selectProduct,normalize};

ready(()=>{
 const form=document.getElementById('productForm'),pid=document.getElementById('productId');if(!form)return;
 const anchor=document.getElementById('reorderLevel')?.closest('label');const box=document.createElement('div');box.className='vcharBox';box.id='vcharEditor';box.innerHTML='<div class="vcharHead"><div><b>🏷️ Características del producto</b><div class="notice">Agrega varios valores: por ejemplo S, M, L y Negro, Azul, Rojo.</div></div><button type="button" class="btn secondary vcharAdd" id="vcharAddCharacteristic">+ Característica</button></div><div id="vcharRows"></div><div class="vcomboBox"><div class="vcharHead"><b>Stock por cada combinación</b><button type="button" class="btn secondary vcharAdd" id="vcharGenerate">Actualizar combinaciones</button></div><div class="notice">Indica cuántas unidades o Kg tienes de cada talla/color.</div><div class="vcomboGrid" id="vcomboGrid"></div></div>';anchor?.parentNode.insertBefore(box,anchor);
 const rows=box.querySelector('#vcharRows'),comboGrid=box.querySelector('#vcomboGrid'); let loadedCombos=[];
 const currentChars=()=>[...rows.children].map(r=>{const sel=r.querySelector('[data-char-name]'),name=sel.value==='Otra'?r.querySelector('[data-char-custom]').value.trim():sel.value;const colorish=name==='Color'||name==='Tono';const values=[...r.querySelectorAll('.vcharValue')].map(v=>({label:v.querySelector('[data-val-label]').value.trim(),color:colorish?v.querySelector('[data-val-color]').value:''})).filter(v=>v.label);return{name,values}}).filter(x=>x.name&&x.values.length);
 function comboKey(vals){return vals.join('||')}
 function generateCombos(){const cs=currentChars(),old=new Map(loadedCombos.map(c=>[comboKey(c.values||[]),c]));comboGrid.querySelectorAll('[data-combo]').forEach(i=>{const k=String(i.dataset.combo||'');if(k)old.set(k,{values:k.split('||'),stock:Math.max(0,Number(i.value)||0)})});if(!cs.length){comboGrid.innerHTML='';return}let sets=[[]];cs.forEach(c=>{sets=sets.flatMap(a=>c.values.map(v=>a.concat(v.label)))});comboGrid.innerHTML=sets.map(vals=>{const o=old.get(comboKey(vals));return '<label class="vcomboLine"><span>'+esc(vals.join(' · '))+'</span><input type="number" min="0" step="0.001" data-combo="'+esc(comboKey(vals))+'" value="'+Number(o?.stock||0)+'" placeholder="Stock"></label>'}).join('');loadedCombos=[...comboGrid.querySelectorAll('[data-combo]')].map(i=>({values:String(i.dataset.combo||'').split('||'),stock:Math.max(0,Number(i.value)||0)}))}
 box.querySelector('#vcharGenerate').onclick=generateCombos;
 let persistTimer=null;
 const persistEditor=()=>{
   const id=String(pid?.value||'').trim();if(!id)return;
   let list=[];try{list=window.products||products||[]}catch{return}
   const p=list.find(x=>String(x.id||'').trim()===id);if(!p)return;
   const characteristics=currentChars();
   const variantCombinations=[...comboGrid.querySelectorAll('[data-combo]')].map(i=>({values:String(i.dataset.combo||'').split('||'),stock:Math.max(0,Number(i.value)||0)}));
   p.characteristics=characteristics;p.variantCombinations=variantCombinations;
   if(variantCombinations.length)p.stock=variantCombinations.reduce((a,c)=>a+Number(c.stock||0),0);
   try{if(typeof save==='function')save()}catch{}
   Promise.resolve(window.syncProductToCloud?.(p)).then(()=>window.vareliaPublicCatalogSync?.()).catch(console.error);
 };
 const schedulePersist=()=>{clearTimeout(persistTimer);persistTimer=setTimeout(persistEditor,450)};
 box.addEventListener('input',schedulePersist);
 box.addEventListener('change',schedulePersist);
 box.addEventListener('click',()=>setTimeout(schedulePersist,40));
 window.VareliaCharacteristics.readEditor=()=>{generateCombos();const characteristics=currentChars();const variantCombinations=[...comboGrid.querySelectorAll('[data-combo]')].map(i=>({values:String(i.dataset.combo||'').split('||'),stock:Math.max(0,Number(i.value)||0)}));loadedCombos=variantCombinations;return{characteristics,variantCombinations}};
 function addRow(data={name:'Talla',values:[]}){
   if(rows.children.length>=8)return window.vareliaToast?.('Puedes usar hasta 8 características.','warn');
   const r=document.createElement('div');r.className='vcharRow';r.innerHTML='<div class="vcharName"><select data-char-name>'+defs.map(x=>'<option>'+x+'</option>').join('')+'</select><input data-char-custom placeholder="Nombre personalizado" style="display:none"></div><div class="vcharValues"></div><div style="display:flex;gap:7px"><button type="button" class="btn secondary vcharAdd" data-add-value>+ Valor</button><button type="button" class="btn danger vcharAdd" data-remove-char>Quitar</button></div>';rows.appendChild(r);
   const sel=r.querySelector('[data-char-name]'),custom=r.querySelector('[data-char-custom]');sel.value=defs.includes(data.name)?data.name:'Otra';custom.style.display=sel.value==='Otra'?'block':'none';custom.value=sel.value==='Otra'?data.name:'';sel.onchange=()=>{custom.style.display=sel.value==='Otra'?'block':'none';r.querySelectorAll('.vcharValue').forEach(x=>x._refreshColor?.())};
   const vals=r.querySelector('.vcharValues');const addVal=(v={label:'',color:''})=>{const colorish=()=>sel.value==='Color'||sel.value==='Tono';const x=document.createElement('div');x.className='vcharValue';x.innerHTML='<input type="text" data-val-label placeholder="'+(colorish()?'Nombre del color':'Valor')+'" value="'+esc(v.label)+'"><input type="color" data-val-color value="'+esc(v.color||'#000000')+'"><button type="button" data-rm-val style="border:0;background:transparent">×</button><div class="vcolorQuick"><button type="button" title="Negro" data-c="#000000" style="background:#000"></button><button type="button" title="Blanco" data-c="#ffffff" style="background:#fff"></button><button type="button" title="Rojo" data-c="#ef4444" style="background:#ef4444"></button><button type="button" title="Azul" data-c="#2563eb" style="background:#2563eb"></button><button type="button" title="Verde" data-c="#16a34a" style="background:#16a34a"></button><button type="button" title="Amarillo" data-c="#facc15" style="background:#facc15"></button><button type="button" title="Rosado" data-c="#ec4899" style="background:#ec4899"></button><button type="button" title="Morado" data-c="#9333ea" style="background:#9333ea"></button></div>';vals.appendChild(x);const picker=x.querySelector('[data-val-color]'),quick=x.querySelector('.vcolorQuick');const refresh=()=>{const on=colorish();picker.style.display=on?'block':'none';quick.style.display=on?'flex':'none';x.querySelector('[data-val-label]').placeholder=on?'Nombre del color':'Valor'};refresh();x.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{picker.value=b.dataset.c;const inp=x.querySelector('[data-val-label]');if(!inp.value)inp.value=b.title});x.querySelector('[data-rm-val]').onclick=()=>x.remove();x._refreshColor=refresh};(data.values||[]).forEach(addVal);if(!data.values?.length)addVal();r.querySelector('[data-add-value]').onclick=()=>addVal();r.querySelector('[data-remove-char]').onclick=()=>r.remove();
 }
 box.querySelector('#vcharAddCharacteristic').onclick=()=>{const presets=['Talla','Color','Marca','Modelo','Material','Tamaño','Presentación','Otra'];addRow({name:presets[Math.min(rows.children.length,presets.length-1)],values:[]})};
 function fill(){rows.innerHTML='';comboGrid.innerHTML='';const p=(window.products||products||[]).find(x=>String(x.id)===String(pid?.value||''));loadedCombos=Array.isArray(p?.variantCombinations)?p.variantCombinations:[];normalize(p?.characteristics).forEach(addRow);setTimeout(generateCombos,0)}
 document.addEventListener('click',e=>{if(e.target.closest('#newProduct,#inventoryNewProduct,[data-edit]'))setTimeout(fill,0)},true);

});
})();