(()=>{
  if(window.__vareliaProfessionalFlow)return;window.__vareliaProfessionalFlow=true;
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();
  ready(()=>{
    const style=document.createElement('style');style.textContent=`.flowRole{display:flex;gap:12px;align-items:flex-start;padding:13px 14px;margin:0 0 14px;border:1px solid color-mix(in srgb,var(--p) 20%,var(--line));border-radius:16px;background:linear-gradient(135deg,color-mix(in srgb,var(--p) 6%,var(--card)),var(--card));box-shadow:0 7px 20px rgba(15,23,42,.05)}.flowRoleIcon{width:38px;height:38px;flex:0 0 38px;border-radius:12px;display:grid;place-items:center;background:color-mix(in srgb,var(--p) 10%,var(--card));font-size:20px}.flowRole strong{display:block;font-size:14px}.flowRole span{display:block;color:var(--muted);font-size:12px;margin-top:2px;line-height:1.45}.flowTag{display:inline-flex!important;width:auto!important;margin-top:7px!important;padding:4px 8px;border-radius:999px;background:var(--bg);font-size:11px!important;font-weight:850;color:var(--p)!important}.flowNavHint{display:block;font-size:10px;font-weight:650;color:#94a3b8;margin-top:2px;line-height:1.2}.nav button.active .flowNavHint{color:#fff;opacity:.82}.inventorySubGroup{display:grid;gap:4px}.inventorySubmenu{display:none;gap:4px;padding-left:14px}.inventorySubGroup.open .inventorySubmenu{display:grid}.inventorySubmenu button{font-size:13px;padding:9px 12px;border-radius:10px}.inventoryParent{display:flex!important;align-items:center;justify-content:space-between}.inventoryArrow{transition:.2s}.inventorySubGroup.open .inventoryArrow{transform:rotate(180deg)}`;document.head.appendChild(style);
    const roles={products:{icon:'📦',title:'Catálogo de productos',desc:'Aquí creas y editas cada producto: nombre, imagen, código de barras, categoría y precios.',tag:'No modifica stock por sí solo'},categories:{icon:'🗂️',title:'Organización del catálogo',desc:'Sirve únicamente para crear y ordenar las categorías de tus productos.',tag:'Organización'},inventory:{icon:'📊',title:'Control de existencias',desc:'Consulta cuánto stock tienes, revisa productos con stock bajo y realiza correcciones cuando el conteo físico sea diferente.',tag:'Consulta y control'},suppliers:{icon:'🤝',title:'Directorio de proveedores',desc:'Guarda los datos de las empresas o personas a quienes compras mercadería.',tag:'Datos de proveedores'},purchases:{icon:'📥',title:'Ingreso de mercadería',desc:'Usa esta sección cuando recibas una compra o reposición. Registra proveedor, cantidades y costos para aumentar el stock correctamente.',tag:'Entradas formales de stock'},sales:{icon:'🛒',title:'Punto de venta',desc:'Registra las ventas. Al confirmar una venta, las unidades salen automáticamente del inventario.',tag:'Salidas por venta'},cash:{icon:'💰',title:'Control de caja',desc:'Muestra y controla el dinero generado por las ventas y los cierres de caja.',tag:'Dinero, no inventario'},appearance:{icon:'🎨',title:'Personalización',desc:'Cambia la apariencia visual de Varelia sin afectar productos, inventario ni ventas.',tag:'Configuración visual'}};
    function addRole(id,data){const sec=document.getElementById(id);if(!sec||sec.querySelector('.flowRole'))return;const head=sec.querySelector('.head');if(!head)return;const box=document.createElement('div');box.className='flowRole';box.innerHTML=`<div class="flowRoleIcon">${data.icon}</div><div><strong>${data.title}</strong><span>${data.desc}</span><span class="flowTag">${data.tag}</span></div>`;head.insertAdjacentElement('afterend',box)}Object.entries(roles).forEach(([id,data])=>addRole(id,data));
    function tuneBulk(){const sec=document.getElementById('bulkScan');if(!sec)return;const h=sec.querySelector('.head h2');if(h)h.textContent='Ajuste rápido de inventario';const p=sec.querySelector('.head .notice');if(p)p.textContent='Para conteos físicos y correcciones rápidas del stock. Las compras normales deben registrarse en Mercadería.';if(!sec.querySelector('.flowRole')){const head=sec.querySelector('.head'),box=document.createElement('div');box.className='flowRole';box.innerHTML='<div class="flowRoleIcon">📲</div><div><strong>Conteo y correcciones rápidas</strong><span>Escanea productos para corregir diferencias entre el stock físico y el registrado.</span><span class="flowTag">Herramienta de Inventario</span></div>';head?.insertAdjacentElement('afterend',box)}const apply=document.getElementById('bulkApply');if(apply)apply.textContent='✓ Confirmar ajuste de inventario'}
    function organizeInventory(){const nav=document.querySelector('.nav'),inv=nav?.querySelector('[data-view="inventory"]'),quick=nav?.querySelector('[data-view="bulkScan"]');if(!nav||!inv||!quick)return;if(document.getElementById('inventorySubGroup'))return;const group=document.createElement('div');group.id='inventorySubGroup';group.className='inventorySubGroup';const parent=document.createElement('button');parent.type='button';parent.className='inventoryParent';parent.innerHTML='<span>📊 Inventario</span><span class="inventoryArrow">⌄</span>';const sub=document.createElement('div');sub.className='inventorySubmenu';const stock=document.createElement('button');stock.type='button';stock.dataset.view='inventory';stock.innerHTML='Existencias<span class="flowNavHint">Stock y alertas</span>';quick.innerHTML='Ajuste rápido<span class="flowNavHint">Conteo y correcciones</span>';inv.replaceWith(group);sub.append(stock,quick);group.append(parent,sub);parent.onclick=()=>group.classList.toggle('open');stock.onclick=e=>{e.preventDefault();try{switchView('inventory')}catch{};group.classList.add('open')};quick.addEventListener('click',()=>group.classList.add('open'))}
    tuneBulk();organizeInventory();setTimeout(()=>{tuneBulk();organizeInventory()},500);setTimeout(()=>{tuneBulk();organizeInventory()},1600);
    const parent=document.querySelector('#supplierGroup .navparent');if(parent&&!parent.dataset.flowNamed){parent.dataset.flowNamed='1';const arrow=parent.querySelector('.arrow')?.outerHTML||'<span class="arrow">⌄</span>';parent.innerHTML=`📦 Compras y proveedores <span class="flowNavHint" style="margin-left:auto;margin-right:8px">Abastecimiento</span>${arrow}`}
  });
})();