(()=>{
  function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn()}
  ready(()=>{
    let scanner=null,target='inventory',busy=false,lastProduct=null;
    const productBtn=document.getElementById('scanForProduct'),inventoryBtn=document.getElementById('scanForInventory'),saleBtn=document.getElementById('scanForSale'),dialog=document.getElementById('scannerDialog'),closeBtn=document.getElementById('closeScanner');
    if(!dialog||(!productBtn&&!inventoryBtn&&!saleBtn))return;
    const modal=dialog.querySelector('.modal');
    if(modal&&!document.getElementById('vareliaReader')){
      const oldVideo=document.getElementById('scannerVideo');if(oldVideo)oldVideo.style.display='none';
      const info=document.createElement('div');info.id='scannerInfo';info.style.cssText='padding:9px 0 12px;color:var(--muted);font-size:13px';info.textContent='Apunta la cámara al código de barras. La lectura será automática.';
      const reader=document.createElement('div');reader.id='vareliaReader';reader.style.cssText='width:100%;min-height:280px;border-radius:16px;overflow:hidden;background:#000';
      const manual=document.createElement('div');manual.style.cssText='display:flex;gap:8px;margin-top:12px';manual.innerHTML='<input id="scannerManualCode" placeholder="O escribe el código manualmente"><button type="button" class="btn primary" id="scannerUseManual">Usar</button>';
      const result=document.createElement('div');result.id='scannerProductResult';result.style.cssText='display:none;margin-top:14px;border:1px solid var(--line);border-radius:18px;padding:14px;background:var(--card);box-shadow:var(--shadow)';
      modal.appendChild(info);modal.appendChild(reader);modal.appendChild(manual);modal.appendChild(result);
      document.getElementById('scannerUseManual').onclick=()=>{const v=document.getElementById('scannerManualCode').value.trim();if(v)finish(v)};
    }
    function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    function loadLib(){return new Promise((resolve,reject)=>{if(window.Html5Qrcode)return resolve();const s=document.createElement('script');s.src='https://unpkg.com/html5-qrcode@2.3.8/html5-qrcode.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
    function norm(v){return String(v??'').trim().replace(/[^0-9A-Za-z]/g,'').toUpperCase()}
    function digits(v){return String(v??'').replace(/\D/g,'')}
    function equivalent(a,b){a=norm(a);b=norm(b);if(!a||!b)return false;if(a===b)return true;const ad=digits(a),bd=digits(b);if(ad&&bd){if(ad===bd)return true;if(ad.replace(/^0+/,'')===bd.replace(/^0+/,''))return true;if(ad.length>=12&&bd.length>=12&&ad.slice(-12)===bd.slice(-12))return true}return false}
    function allStoredProducts(){const out=[];try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||!/product/i.test(k))continue;let v;try{v=JSON.parse(localStorage.getItem(k)||'null')}catch{continue}if(Array.isArray(v))for(const x of v)if(x&&typeof x==='object'&&('barcode'in x||'name'in x))out.push(x)}}catch{}return out}
    function findProduct(code){let pools=[];try{if(typeof products!=='undefined'&&Array.isArray(products))pools.push(...products)}catch{}pools.push(...allStoredProducts());const p=pools.find(x=>equivalent(x?.barcode,code));if(!p)return null;try{if(typeof products!=='undefined'&&Array.isArray(products)){const live=products.find(x=>String(x.id)===String(p.id))||products.find(x=>equivalent(x.barcode,code));if(live)return live;products.push(p)}}catch{}return p}
    function persistProducts(){try{if(typeof K!=='undefined'&&K.products&&typeof products!=='undefined')localStorage.setItem(K.products,JSON.stringify(products.map(p=>{const c={...p};delete c.image;return c})));if(typeof save==='function')save()}catch(e){console.warn(e)}}
    function selectedInventoryProduct(){try{if(typeof inventoryProductId!=='undefined'&&inventoryProductId&&typeof products!=='undefined')return products.find(x=>String(x.id)===String(inventoryProductId))||null}catch{}return null}
    async function openScanner(which){if(busy)return;target=which;busy=true;lastProduct=null;const result=document.getElementById('scannerProductResult');if(result)result.style.display='none';try{if(!window.isSecureContext){alert('Para usar la cámara debes abrir Varelia con https://');return}if(!navigator.mediaDevices?.getUserMedia){alert('Este navegador no permite usar la cámara. Abre Varelia directamente en Google Chrome.');return}await loadLib();if(typeof dialog.showModal==='function'&&!dialog.open)dialog.showModal();scanner=new Html5Qrcode('vareliaReader');const formats=[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.CODE_128,Html5QrcodeSupportedFormats.CODE_39,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E,Html5QrcodeSupportedFormats.QR_CODE];await scanner.start({facingMode:'environment'},{fps:12,qrbox:{width:280,height:150},formatsToSupport:formats,aspectRatio:1.777},text=>finish(text),()=>{})}catch(e){try{if(dialog.open)dialog.close()}catch{}alert('No se pudo abrir la cámara. Verifica el permiso de cámara en Chrome.')}finally{busy=false}}
    async function stopCameraOnly(){try{if(scanner){await scanner.stop();await scanner.clear()}}catch{}scanner=null}
    async function stop(){await stopCameraOnly();try{if(dialog.open)dialog.close()}catch{}}
    function showProductCard(p,code){lastProduct=p;const result=document.getElementById('scannerProductResult');const reader=document.getElementById('vareliaReader');if(reader)reader.style.display='none';const img=p.image?`<img src="${p.image}" style="width:96px;height:96px;object-fit:cover;border-radius:16px;border:1px solid var(--line)">`:`<div style="width:96px;height:96px;border-radius:16px;background:var(--bg);display:grid;place-items:center;color:var(--muted);font-size:12px">Sin imagen</div>`;result.innerHTML=`<div style="display:flex;gap:12px;align-items:center">${img}<div style="min-width:0;flex:1"><div style="font-size:20px;font-weight:900">${esc(p.name||'Producto')}</div><div class="meta">Código: ${esc(code)}</div><div style="margin-top:6px;font-size:16px"><b>Stock: ${Number(p.stock||0)} ${esc(p.unit||'Unidad')}</b></div><div style="margin-top:4px;color:var(--p);font-size:18px;font-weight:900">S/ ${Number(p.sellPrice||0).toFixed(2)}</div></div></div><div style="display:grid;grid-template-columns:92px 1fr 1fr;gap:8px;margin-top:14px"><input id="scannerActionQty" type="number" min="1" value="1" style="text-align:center"><button type="button" class="btn secondary" id="scannerIncrease">➕ Aumentar</button><button type="button" class="btn primary" id="scannerSell">🛒 Vender</button></div><button type="button" class="btn secondary" id="scannerAgain" style="width:100%;margin-top:9px">📷 Escanear otro</button>`;result.style.display='block';
      document.getElementById('scannerIncrease').onclick=()=>{const q=Math.max(1,Math.floor(+document.getElementById('scannerActionQty').value||1));const before=+p.stock||0;p.stock=before+q;try{if(typeof addMovement==='function')addMovement(p,'add',q,before,p.stock,'Escáner')}catch{}persistProducts();showProductCard(p,code)};
      document.getElementById('scannerSell').onclick=()=>{const q=Math.max(1,Math.floor(+document.getElementById('scannerActionQty').value||1));if((+p.stock||0)<q)return alert('No hay suficiente stock.');try{if(typeof openSale==='function')openSale();for(let i=0;i<q;i++)if(typeof addToCart==='function')addToCart(p);stop()}catch(e){alert('No se pudo agregar a la venta.')}};
      document.getElementById('scannerAgain').onclick=()=>{result.style.display='none';if(reader)reader.style.display='block';openScanner(target)};
    }
    async function finish(code){code=norm(code);if(!code)return;await stopCameraOnly();let p=findProduct(code);
      if(target==='product'&&!p){const el=document.getElementById('barcode');if(el){el.value=code;el.dispatchEvent(new Event('input',{bubbles:true}))}try{if(dialog.open)dialog.close()}catch{}return}
      if(target==='inventory'){const el=document.getElementById('inventoryCode');if(el){el.value=code;el.dispatchEvent(new Event('input',{bubbles:true}))}if(!p){const selected=selectedInventoryProduct();if(selected){selected.barcode=code;persistProducts();p=selected}}}
      if(target==='sale'){const el=document.getElementById('saleSearch');if(el){el.value=code;el.dispatchEvent(new Event('input',{bubbles:true}))}}
      if(p){showProductCard(p,code);return}
      alert('Código leído: '+code+'\nNo pude encontrar el producto registrado.');try{if(dialog.open)dialog.close()}catch{}
    }
    if(productBtn)productBtn.onclick=e=>{e.preventDefault();openScanner('product')};if(inventoryBtn)inventoryBtn.onclick=e=>{e.preventDefault();openScanner('inventory')};if(saleBtn)saleBtn.onclick=e=>{e.preventDefault();openScanner('sale')};if(closeBtn)closeBtn.onclick=e=>{e.preventDefault();stop()};dialog.addEventListener('cancel',e=>{e.preventDefault();stop()});
  })
})();