(()=>{
const SUPABASE_URL='https://onvdcaohnftrjunwdvjp.supabase.co';
const SUPABASE_KEY=atob('c2JfcHVibGlzaGFibGVfYnoyejV1Z2xmX0VBTEplenF2NHJDd19TNzNHTU5yaA==');
if(!window.supabase){console.error('Supabase no cargó');return;}
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,flowType:'pkce'}});
window.vareliaSupabase=sb;
const style=document.createElement('style');style.textContent=`body.varelia-auth-locked>.top,body.varelia-auth-locked>.shell,body.varelia-auth-locked>.fab{display:none!important}#vareliaAuth{position:fixed;inset:0;z-index:99999;display:none;align-items:center;justify-content:center;padding:20px;background:linear-gradient(145deg,#f8fafc,#eef2ff)}#vareliaAuth.show{display:flex}#vareliaAuth *{box-sizing:border-box}.va-card{width:min(100%,430px);background:#fff;border:1px solid #e5e7eb;border-radius:28px;padding:26px;box-shadow:0 24px 60px rgba(15,23,42,.14)}.va-brand{display:flex;align-items:center;gap:12px;margin-bottom:18px}.va-logo{width:52px;height:52px;border-radius:17px;background:linear-gradient(135deg,#7c3aed,#4f46e5);color:#fff;display:grid;place-items:center;font-weight:950;font-size:22px}.va-title{margin:0;font-size:26px}.va-sub{margin:3px 0 0;color:#64748b;font-size:13px}.va-tabs{display:grid;grid-template-columns:1fr 1fr;background:#f1f5f9;border-radius:14px;padding:4px;margin:16px 0}.va-tab{border:0;border-radius:11px;padding:10px;background:transparent;font-weight:850}.va-tab.active{background:#fff;color:#4f46e5;box-shadow:0 3px 10px #0f172a12}.va-form{display:grid;gap:11px}.va-form label{display:grid;gap:6px;font-size:13px;font-weight:800}.va-form input{border:1px solid #dbe2ea;border-radius:14px;padding:12px 13px;background:#fff;color:#111827;outline:none}.va-form input:focus{border-color:#6366f1;box-shadow:0 0 0 3px #6366f11c}.va-btn{border:0;border-radius:14px;padding:13px 15px;background:linear-gradient(135deg,#7c3aed,#4f46e5);color:#fff;font-weight:900;margin-top:4px}.va-msg{min-height:20px;margin:10px 0 0;font-size:13px;color:#475569}.va-msg.error{color:#b91c1c}.va-msg.ok{color:#047857}.va-hide{display:none!important}#vareliaUserBar{position:static;z-index:90;display:none;gap:8px;align-items:center;justify-content:space-between;width:100%;margin:0 0 16px;background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:8px 8px 8px 11px;box-shadow:0 8px 22px #0f172a18;font-size:12px;color:#111827}#vareliaUserEmail{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.vub-btn{border:0;border-radius:999px;padding:8px 11px;background:#f1f5f9;font-weight:800;flex:0 0 auto}`;document.head.appendChild(style);
const auth=document.createElement('div');auth.id='vareliaAuth';auth.innerHTML=`<div class="va-card"><div class="va-brand"><div class="va-logo">V</div><div><h1 class="va-title">Varelia</h1><p class="va-sub">Ventas · Inventario · Caja</p></div></div><div class="va-tabs"><button class="va-tab active" data-va-tab="login">Iniciar sesión</button><button class="va-tab" data-va-tab="register">Crear cuenta</button></div><form class="va-form" id="vaLogin"><label>Correo<input id="vaLoginEmail" type="email" autocomplete="email" required></label><label>Contraseña<input id="vaLoginPass" type="password" autocomplete="current-password" minlength="6" required></label><button class="va-btn">Entrar a Varelia</button></form><form class="va-form va-hide" id="vaRegister"><label>Tu nombre<input id="vaName" autocomplete="name" required></label><label>Nombre del negocio<input id="vaBusiness" required></label><label>Correo<input id="vaEmail" type="email" autocomplete="email" required></label><label>Contraseña<input id="vaPass" type="password" autocomplete="new-password" minlength="6" required></label><button class="va-btn">Crear mi cuenta</button></form><div id="vaMsg" class="va-msg"></div></div>`;document.body.appendChild(auth);
const userBar=document.createElement('div');userBar.id='vareliaUserBar';userBar.innerHTML='<span id="vareliaUserEmail"></span><button class="vub-btn" id="vareliaLogout">Salir</button>';
const side=document.querySelector('.side');if(side)side.insertBefore(userBar,side.firstChild);else document.body.appendChild(userBar);
const $=s=>document.querySelector(s),msg=(t,type='')=>{const m=$('#vaMsg');if(!m)return;m.textContent=t;m.className='va-msg '+type};
function showAuth(){document.body.classList.add('varelia-auth-locked');auth.classList.add('show');userBar.style.display='none'}
function showApp(user){document.body.classList.remove('varelia-auth-locked');auth.classList.remove('show');$('#vareliaUserEmail').textContent=user?.email||'';userBar.style.display='flex'}
async function ensureAccount(user){let {data:profile,error}=await sb.from('profiles').select('id,business_id,role').eq('id',user.id).maybeSingle();if(error)throw error;if(profile)return profile;let pending={};try{pending=JSON.parse(localStorage.getItem('varelia_pending_account')||'{}')}catch{}const meta=user.user_metadata||{};const fullName=pending.fullName||meta.full_name||meta.name||user.email?.split('@')[0]||'Usuario';const businessName=pending.businessName||meta.business_name||('Negocio de '+fullName);const {data:biz,error:be}=await sb.from('businesses').insert({name:businessName,owner_id:user.id}).select('id').single();if(be)throw be;const {data:pr,error:pe}=await sb.from('profiles').insert({id:user.id,full_name:fullName,business_id:biz.id,role:'owner'}).select('id,business_id,role').single();if(pe)throw pe;localStorage.removeItem('varelia_pending_account');return pr}
async function enterWithSession(session){if(!session?.user){showAuth();return}try{await ensureAccount(session.user);showApp(session.user)}catch(e){showAuth();msg('No se pudo cargar tu cuenta: '+(e.message||e),'error')}}
auth.addEventListener('click',e=>{const b=e.target.closest('[data-va-tab]');if(!b)return;document.querySelectorAll('.va-tab').forEach(x=>x.classList.toggle('active',x===b));$('#vaLogin').classList.toggle('va-hide',b.dataset.vaTab!=='login');$('#vaRegister').classList.toggle('va-hide',b.dataset.vaTab!=='register');msg('')});
$('#vaLogin').addEventListener('submit',async e=>{e.preventDefault();msg('Ingresando...');const {data,error}=await sb.auth.signInWithPassword({email:$('#vaLoginEmail').value.trim(),password:$('#vaLoginPass').value});if(error){msg(error.message,'error');return}await enterWithSession(data.session)});
$('#vaRegister').addEventListener('submit',async e=>{e.preventDefault();const fullName=$('#vaName').value.trim(),businessName=$('#vaBusiness').value.trim(),email=$('#vaEmail').value.trim(),password=$('#vaPass').value;localStorage.setItem('varelia_pending_account',JSON.stringify({fullName,businessName}));msg('Creando cuenta...');const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:fullName,business_name:businessName}}});if(error){msg(error.message,'error');return}if(data.session){await enterWithSession(data.session)}else{msg('Cuenta creada. Revisa tu correo para confirmar y luego inicia sesión.','ok')}});
$('#vareliaLogout').addEventListener('click',async()=>{await sb.auth.signOut();showAuth();msg('Sesión cerrada.','ok')});
sb.auth.onAuthStateChange((_event,session)=>{if(session)enterWithSession(session)});
(async()=>{
  showAuth();
  const params=new URLSearchParams(location.search);
  const code=params.get('code');
  if(code){
    msg('Completando inicio con Google...');
    const {data,error}=await sb.auth.exchangeCodeForSession(code);
    if(error){msg('No se pudo completar Google: '+error.message,'error');return}
    history.replaceState({},document.title,location.origin+location.pathname);
    await enterWithSession(data.session);
    return;
  }
  const {data,error}=await sb.auth.getSession();
  if(error){msg(error.message,'error');return}
  await enterWithSession(data.session);
})();
})();