(()=>{if(window.__vareliaWeightSales)return;window.__vareliaWeightSales=true;
const all=()=>{try{return Array.isArray(products)?products:[]}catch{return[]}},isKg=p=>String(p?.unit||'').trim().toLowerCase()==='kg';
const findProduct=(id,barcode,name)=>all().find(x=>String(x.id)===String(id))||all().find(x=>barcode&&String(x.barcode||'').trim()===String(barcode).trim())||all().find(x=>name&&String(x.name||'').trim().toLowerCase()===String(name).trim().toLowerCase());
const st=document.createElement('style');st.textContent='.vwDlg{border:0;border-radius:20px;padding:0;width:min(430px,92vw);background:var(--card);color:var(--ink);box-shadow:0 24px 70px #0005}.vwDlg::backdrop{background:#0f172a99}.vwBody{padding:18px}.vwHead{display:flex;justify-content:space-between;align-items:center;gap:12px}.vwHead h3{margin:0}.vwClose{border:0;background:transparent;color:var(--ink);font-size:28px}.vwInfo{margin:6px 0 15px;color:var(--muted);font-size:13px}.vwQuick{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.vwQuick button{padding:14px;border:1px solid var(--line);border-radius:13px;background:var(--bg);color:var(--ink);font-weight:900;display:grid;gap:4px;text-align:left}.vwQuick button small{color:var(--p);font-size:14px;font-weight:950}.vwQuick button.active{border:2px solid var(--p);background:color-mix(in srgb,var(--p) 8%,var(--card))}.vwManual{display:grid;grid-template-columns:1fr 110px;gap:9px;margin-top:12px}.vwManual input,.vwManual select{width:100%;padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--card);color:var(--ink)}.vwCalc{margin-top:14px;padding:13px;border-radius:14px;background:var(--bg);display:flex;justify-content:space-between;align-items:center}.vwCalc strong{font-size:24px;color:var(--p)}.vwAdd{width:100%;margin-top:12px;padding:14px}';document.head.appendChild(st);
const d=document.createElement('dialog');d.className='vwDlg';d.innerHTML='<div class="vwBody"><div class="vwHead"><h3 id="vwName">Venta por peso</h3><button class="vwClose" type="button">×</button></div><div class="vwInfo" id="vwInfo"></div><div class="vwQuick"><button data-g="100"><span>100 g</span><small></small></button><button data-g="250"><span>250 g</span><small></small></button><button data-g="500"><span>500 g</span><small></small></button><button data-g="1000"><span>1 kg</span><small></small></button></div><div class="vwManual"><input id="vwValue" type="number" inputmode="decimal" min="0.001" step="0.001" placeholder="Escribe el peso"><select id="vwUnit"><option value="g">gramos</option><option value="kg">kg</option></select></div><div class="vwCalc"><span id="vwQty">0 kg</span><strong id="vwTotal">S/ 0.00</strong></div><button class="btn primary vwAdd" id="vwAdd" type="button">Agregar a la venta</button></div>';document.body.appendChild(d);
let current=null;const val=d.querySelector('#vwValue'),unit=d.querySelector('#vwUnit'),kg=()=>Math.max(0,Number(val.value)||0)*(unit.value==='g'?.001:1);
const render=()=>{const q=kg(),grams=Math.round(q*1000);d.querySelector('#vwQty').textContent=q?(grams+' g · '+q.toFixed(3)+' kg'):'0 g';d.querySelector('#vwTotal').textContent='S/ '+(q*Number(current?.sellPrice||0)).toFixed(2);d.querySelectorAll('[data-g]').forEach(b=>b.classList.toggle('active',Number(b.dataset.g)===grams))};
const open=p=>{current=p;d.querySelectorAll('[data-g]').forEach(b=>{b.querySelector('small').textContent='S/ '+(Number(p.sellPrice||0)*Number(b.dataset.g)/1000).toFixed(2)});d.querySelector('#vwName').textContent=p.name;d.querySelector('#vwInfo').textContent='Precio por kg: S/ '+Number(p.sellPrice||0).toFixed(2)+' · Stock '+Number(p.stock||0).toFixed(3)+' kg';val.value='';unit.value='g';render();d.showModal()};
d.querySelector('.vwClose').onclick=()=>d.close();d.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{val.value=b.dataset.g;unit.value='g';render();val.focus()});val.oninput=render;unit.onchange=render;
d.querySelector('#vwAdd').onclick=()=>{const q=kg();if(!current||q<=0)return window.vareliaToast?.('Ingresa un peso válido.','warn');if(q>Number(current.stock||0))return window.vareliaToast?.('Stock disponible: '+Number(current.stock||0).toFixed(3)+' kg','warn');window.__vareliaAddingWeight=true;let ok=false;try{if(window.VareliaPOS?.addProduct){ok=window.VareliaPOS.addProduct(current,q)!==false}else{addToCart(current,q);ok=true}if(ok){try{if(typeof renderCart==='function')renderCart()}catch{}try{window.VareliaPOS?.sync?.()}catch{}}}finally{window.__vareliaAddingWeight=false}if(!ok)return;window.vareliaSound?.('add');window.vareliaToast?.(current.name+' · '+Math.round(q*1000)+' g agregado','ok');d.close();val.value='';setTimeout(()=>window.VareliaPOS?.sync?.(),80)}
document.addEventListener('click',e=>{const add=e.target.closest?.('[data-add]');if(add){const p=all().find(x=>String(x.id)===String(add.dataset.add));if(isKg(p)){e.preventDefault();e.stopImmediatePropagation();try{if(typeof openSale==='function')openSale()}catch{};open(p);return}}const b=e.target.closest?.('#vposSuggestions [data-pos-id]');if(!b)return;const p=all().find(x=>String(x.id)===String(b.dataset.posId));if(!isKg(p))return;e.preventDefault();e.stopImmediatePropagation();open(p)},true);
document.addEventListener('keydown',e=>{const input=e.target.closest?.('#vposInput');if(!input||e.key!=='Enter')return;const q=String(input.value||'').trim().toLowerCase(),p=all().find(x=>String(x.barcode||'').trim().toLowerCase()===q)||all().find(x=>String(x.name||'').trim().toLowerCase()===q);if(!isKg(p))return;e.preventDefault();e.stopImmediatePropagation();open(p);input.value=''},true);
// En la caja principal, cualquier producto Kg debe abrir el selector antes de sumarse como unidad.
document.addEventListener('click',e=>{
 const row=e.target.closest?.('#vareliaPosSales .vposItem');
 if(!row)return;
 const id=row.querySelector('[data-pos-plus]')?.dataset.posPlus||row.querySelector('[data-pos-qty]')?.dataset.posQty;
 const p=findProduct(id,'',row.querySelector('.vposItemName')?.textContent);
 if(!isKg(p))return;
 const plus=e.target.closest('[data-pos-plus]'),qty=e.target.closest('[data-pos-qty]');
 if(plus){e.preventDefault();e.stopImmediatePropagation();open(p)}
 if(qty){e.preventDefault();e.stopImmediatePropagation();open(p)}
},true);
window.addEventListener('varelia:central-stock-updated',()=>setTimeout(()=>window.VareliaPOS?.sync?.(),0));
window.VareliaWeightSale={open};})();