'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
const money=n=>'S/ '+Number(n||0).toFixed(2),cfg=window.VARELIA_CONFIG||{};
let db=null,user=null,business=null,products=[],currentView='catalog',syncStop=null;
function show(id){for(const x of ['setup','auth','new-business','workspace'])$(x).classList.toggle('hidden',x!==id);$('nav').classList.toggle('hidden',id!=='workspace');$('logout').classList.toggle('hidden',id!=='workspace');}
function status(t){$('connection').textContent=t;}
function view(v){currentView=v;for(const x of ['sale','catalog','inventory','history','admin','settings'])$('view-'+x).classList.toggle('hidden',x!==v);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('section-title').textContent=({sale:'Venta',catalog:'Catálogo',inventory:'Inventario',history:'Historial',admin:'Administración',settings:'Ajustes'})[v];$('add-product').classList.toggle('hidden',v!=='catalog');}
async function reloadProducts(){if(!db||!business)return;const {data,error}=await db.from('products').select('id,name,sku,price,stock').eq('business_id',business.id).order('name');if(error){status('Error al cargar productos');return;}products=data||[];renderProducts();}
function renderProducts(){const q=$('search').value.toLowerCase();$('products').innerHTML=products.filter(p=>(p.name+' '+(p.sku||'')).toLowerCase().includes(q)).map(p=>'<article class="product"><h3>'+esc(p.name)+'</h3><p>'+esc(p.sku||'Sin código')+'</p><strong>'+money(p.price)+'</strong><p class="muted">Stock: '+Number(p.stock)+'</p></article>').join('')||'<div class="panel">No hay productos. Crea el primero.</div>';$('inventory').innerHTML=products.map(p=>'<div class="row"><span>'+esc(p.name)+'</span><strong>'+Number(p.stock)+'</strong></div>').join('')||'<p>No hay productos.</p>';}
async function reloadOrders(){if(!business)return;const {data,error}=await db.from('public_orders').select('order_number,status,total,created_at,customer_name').eq('business_id',business.id).order('created_at',{ascending:false}).limit(20);if(error){$('orders').textContent='Los pedidos se mostrarán cuando se instale el módulo de pedidos.';return;}$('orders').innerHTML='<h3>Pedidos recientes</h3>'+(data||[]).map(o=>'<div class="row"><span>'+esc(o.order_number)+' · '+esc(o.customer_name)+' · '+esc(o.status)+'</span><strong>'+money(o.total)+'</strong></div>').join('')||'<p>No hay pedidos.</p>';}
async function startBusiness(b){business=b;$('business-title').textContent=b.name;$('account').textContent=user.email;show('workspace');view('catalog');await Promise.all([reloadProducts(),reloadOrders()]);if(syncStop)syncStop();syncStop=window.VareliaSync.connect(db,b.id,{products:reloadProducts,public_orders:reloadOrders},s=>status(({connected:'☁️ Sincronizado',reconnecting:'Reconectando…',offline:'Sin conexión',disconnected:'Desconectado'})[s]||s));}
async function loadBusiness(){const {data,error}=await db.from('businesses').select('id,name').order('created_at').limit(1);if(error){$('business-error').textContent=error.message;show('new-business');return;}if(data?.length)await startBusiness(data[0]);else{show('new-business');status('Crea tu negocio');}}
async function init(){const savedColor=localStorage.getItem('varelia-theme');if(/^#[0-9a-f]{6}$/i.test(savedColor||'')){$('theme').value=savedColor;document.documentElement.style.setProperty('--blue',savedColor);}if(!cfg.supabaseUrl||!cfg.supabaseAnonKey||!window.supabase){show('setup');status('Falta configurar Supabase');return;}db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);const {data:{session}}=await db.auth.getSession();user=session?.user||null;if(user)await loadBusiness();else{show('auth');status('Inicia sesión');}db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){if(syncStop)syncStop();syncStop=null;business=null;user=null;show('auth');status('Inicia sesión');}else if(event==='SIGNED_IN'&&!user){user=session.user;setTimeout(()=>loadBusiness().catch(console.error),0);}});}
$('google').onclick=async()=>{const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)$('auth-error').textContent=error.message;};
$('logout').onclick=async()=>{if(syncStop)syncStop();await db.auth.signOut();};
$('business-form').onsubmit=async e=>{e.preventDefault();$('business-error').textContent='';const {data,error}=await db.from('businesses').insert({owner_user_id:user.id,name:$('business-name').value.trim()}).select('id,name').single();if(error){$('business-error').textContent=error.message;return;}await startBusiness(data);};
$('add-product').onclick=()=>$('product-dialog').showModal();$('cancel-product').onclick=()=>$('product-dialog').close();
$('product-form').onsubmit=async e=>{e.preventDefault();$('product-error').textContent='';const price=Number($('product-price').value);if(!Number.isFinite(price)||price<0)return;const {error}=await db.from('products').insert({business_id:business.id,name:$('product-name').value.trim(),sku:$('product-sku').value.trim()||null,price});if(error){$('product-error').textContent=error.message;return;}$('product-dialog').close();$('product-form').reset();await reloadProducts();};
$('search').oninput=renderProducts;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
$('theme').oninput=e=>{const color=e.target.value;document.documentElement.style.setProperty('--blue',color);localStorage.setItem('varelia-theme',color);};
$('publish-help').onclick=()=>$('public-link').textContent='Para publicar, configura storefront_settings y storefront_products de este negocio en Supabase. No publiques sin controles anti-spam.';
init().catch(e=>{status('Error de conexión');$('auth-error').textContent=e.message;});
