plugins {
    id "com.android.application"
}

android {
    namespace "tech.vareliastore.app"
    compileSdk 35

    defaultConfig {
        applicationId "tech.vareliastore.app"
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName "1.0.4"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.camera:camera-core:1.4.1"
    implementation "androidx.camera:camera-camera2:1.4.1"
    implementation "androidx.camera:camera-lifecycle:1.4.1"
    implementation "androidx.camera:camera-view:1.4.1"
    implementation "com.google.mlkit:barcode-scanning:17.3.0"
}
